server:
  port: 14583
  max-http-request-header-size: 32KB
  undertow:
    always-set-keep-alive: true
#    options:
#      server:
#      socket:

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB