
server:
  port: 14581
  max-http-request-header-size: 32KB
 # forward-headers-strategy: FRAMEWORK
  compression:
    enabled: true
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
